package com.nikvay.doctorapplication.apicallcommon;

public class EndApi extends BaseApi {
    public static final String LOGIN = "ws-login";
    public static final String SERVICE_LIST = "ws-service";
    public static final String ADD_NEW_PATIENT = "ws-addpatient";
    public static final String UPDATE_PATIENT = "ws-editPatient";
    public static final String PATIENT_LIST = "ws-listpatient";
    public static final String UPDATE_SERVICE_LIST = "ws-editservice";
    public static final String ADD_NEW_SERVICE = "ws-addservice";
    public static final String APPOINTMENT_TIME_SLOT = "ws-appointmentPatient";
    public static final String ADD_APPOINTMENT = "ws-addAppointmentPatient";
    public static final String LIST_APPOINTMENT = "ws-listAppointment";
    public static final String APPOINTMENT_LIST_COUNT = "ws-listAppointmentCount";
    public static final String APPOINTMENT_EDIT = "ws-editAppointment";
    public static final String ADD_CLASS = "ws-classes";
    public static final String UPDATE_CLASS = "ws-editClass";
    public static final String LIST_CLASS = "ws-classesList";
    public static final String LIST_PAYMENT = "ws-listPaymentHistory";
    public static final String NOTIFICATION_LIST = "ws-listAptNotificetion";
    public static final String NOTIFICATION_CLEAR = "ws-deleteNotificetion";
    public static final String CHANGE_PASSWORD = "ws-userChangePasswordDoctor";
    public static final String ADDPAYMENT = "ws-addPayment";
    public static final String APPOINTMENT_HISTORY = "ws-appointment-list-for-doctor";
    public static final String PRESCRIPTION_HISTORY = "ws-listPrescription";
    public static final String ADD_PRESCRIPTION = "ws-addPrescription";
    public static final String ENQUIRY_LIST = "ws-enquiry-list-for-doctor";
    public static final String ENQUIRY_REPLY = "ws-enquiry-reply";
    public static final String ADD_PRESCRIPTION_DOCUMENT = "ws-add-prescription-document";
    public static final String LIST_PRESCRIPTION_DOCUMENT = "ws-list-prescription-document";
    public static final String DOCTORlIST = "ws-listDoctor";
    public static final String ADD_NEW_DOCTOR = "ws-doctor-add";
    public static final String LIST_ADMIN_DEPARTMENT= "ws-department-list";
    public static final String ADD_ADMIN_DEPARTMENT= "ws-department-add";
    public static final String PATIENT_LIST_ADMIN= "ws-patient-list";
    public static final String ADD_PATIENT_ADMIN= "ws-patient-add";
    public static final String LIST_ADMIN_SERVICE= "ws-service-list";
    public static final String ADD_ADMIN_SERVICE= "ws-service-add";
    public static final String ADD_CLASS_SESSION= "ws-add-session";
    public static final String DOCTORAPPOINTMENTSLOT = "ws-doctorAppointmentSlot";
    public static final String CANCLEAPPOINTMENT = "ws-cancel-appointment-doctor";
    public static final String LIST_SESSION = "ws-list-session";
    public static final String EDIT_SESSION = "ws-edit-session";
}